php_role:
  common:
    packages:
      - php7.0-common
      - php7.0-cli
      - php7.0-intl
      - php7.0-curl
      - php7.0-cgi
      - php7.0-fpm
      - php7.0-mysql
      - php7.0-gd
      - php-pear
      - php7.0-dev
  extensions:
    packages:
      - apcu
