php_role:
  common:
    packages:
      - php71w-common
      - php71w-cli
      - php71w-intl
      - php71w-curl
      - php71w-mysqlnd
      - php71w-gd
      - php71w-pear
      - php71w-opcache
      - php71w-mbstring
      - php71w-xml
      - php71w-pecl-apcu
      - php71w-pecl-imagick
      - php71w-json
      - php71w-zip
      - php71w-readline
      - php71w-soap
