php_role:
  common:
    packages:
      - php7.4-common
      - php7.4-cli
      - php7.4-json
      - php7.4-xml
      - php7.4-zip
      - php7.4-mbstring
      - php7.4-intl
      - php7.4-opcache
      - php7.4-readline
      - php7.4-soap
      - php7.4-curl
      - php7.4-gd
      - php7.4-imagick
      - php-pear
      - php7.4-mysql
      - php7.4-apcu
