---

- name: cleaning destination folder
  file: path={{ stores_dir }}/{{ item.key }} state=absent
  when: (item.value.cart.dist is defined)
  ignore_errors: true
  with_dict: '{{stores}}'
  tags:
    - cscart
    - deploy

- name: creating projects directories
  file:
    path={{ stores_dir }}/{{ item.key }}
    state=directory
    owner={{ deploy.user }}
    group={{ deploy.group }}
    mode=755
  ignore_errors: true
  with_dict: '{{stores}}'
  tags:
    - apache
    - nginx
    - php
    - cscart
    - deploy

- name: copying repository and unpacking archive
  unarchive: src={{ item.value.cart.dist }} dest={{ stores_dir }}/{{ item.key }} copy=no
  when: (item.value.cart.dist is defined)
  with_dict: '{{stores}}'
  tags:
    - cscart
    - deploy