---

- name: installing packages via yum
  yum:
    name={{ item }}
    state=present
  with_items: '{{logrotate_role.packages}}'
  when: ansible_os_family == "RedHat"
  tags:
    - logrotate

- name: installing packages via apt
  apt:
    name={{ item }}
    state=present
  with_items: '{{logrotate_role.packages}}'
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
  tags:
    - logrotate