- name: loading configs
  template: src={{ item }}.j2 dest=/etc/nginx/{{ item }}
  with_items:
    - "conf-available/upstream.conf"
    - "xtra/fastcgi_params.conf"
    - "xtra/fastcgi_params_ssl.conf"
  tags:
    - nginx

- name: enabling configs
  file:
    src=/etc/nginx/conf-available/{{ item }}
    dest=/etc/nginx/conf-enabled/{{ item }}
    state=link
  with_items:
    - "upstream.conf"
  tags:
    - nginx

- name: loading vhosts
  template:
    src=sites-available/default.conf.j2
    dest=/etc/nginx/sites-available/{{ item.key }}.conf
  with_dict: '{{stores}}'
  tags:
    - nginx

- name: enabling vhosts
  file:
    src=/etc/nginx/sites-available/{{ item.key }}.conf
    dest=/etc/nginx/sites-enabled/{{ item.key }}.conf
    state=link
  with_dict: '{{stores}}'
  tags:
    - nginx

- name: restarting service
  command: service {{ nginx_role.service }} restart
  ignore_errors: true
  tags:
    - nginx